[[constraint]]
  branch = "master"
  name = "github.com/vektah/gqlgen"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/websocket"

[[constraint]]
  version = "2.2.6"
  name = "gopkg.in/alecthomas/kingpin.v2"

[[constraint]]
  branch = "master"
  name = "github.com/gchaincl/sqlhooks"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-sqlite3"

[[constraint]]
  branch = "master"
  name = "github.com/vektah/dataloaden"
