[[constraint]]
  branch = "master"
  name = "github.com/vektah/gqlgen"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/websocket"

[[constraint]]
  version = "2.2.6"
  name = "gopkg.in/alecthomas/kingpin.v2"

[[constraint]]
  branch = "master"
  name = "github.com/gchaincl/sqlhooks"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-sqlite3"

[[constraint]]
  branch = "master"
  name = "github.com/stellar/go"

[[constraint]]
  version = "1.1.11"
  name = "gopkg.in/mgutz/dat.v1"

[[constraint]]
  branch = "mgutz/v2"
  name = "github.com/mgutz/logxi"
